/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradeltest;

public class App {
    public static void main(String[] args) {
        int[] prueba = {1,2,3,56,78}; 
        
         Gestor g = new Gestor(prueba);
         g.comptarElements();
         g.retornarPrimer();
         g.retornarDarrer();
         g.retornarTercer();
         g.sumaElements();
         g.mitjanaElements();
         
     }
 }
 
